### PR TITLE
Lyap for master

### PR DESCRIPTION
**Pull request by dapias**
I made the code to calculate the Lyapunov spectrum of a billiard for a non-magnetic particle. It is separated from the core of the program. I wanted to illustrate it with a pair of examples (making add them to the documentation) but I am not sure about how to use Documenter.jl . I put here a piece of code to test it:

```julia
using DynamicBilliards

radius = 1.0
l = 1.5 
bt = billiard_polygon(6,l; setting = "periodic")
disc = Disk([0., 0.], radius)
push!(bt, disc)
p = randominside(bt)
t = 5000.0

exps = lyapunovspectrum(p, bt, t)
```

### CODE REVIEW

**Comment by dapias** [comment]
I made the code to calculate the Lyapunov spectrum of a billiard for a non-magnetic particle. It is separated from the core of the program. I wanted to illustrate it with a pair of examples (making add them to the documentation) but I am not sure about how to use Documenter.jl

**Comment by Datseris** [comment]
Very very nice! I have one more request: would you be kind to also write a a basic test for the lyapunov exponents? Just take a piece of code that you have already used and make it a new test file in /test/new_file.jl . The `@test` command simply makes a "Test" if a Boolean expression is `true`. If you see my tests you will understand how to use it right away!

Now, about the documentation. It is very simple if you are familiar on how to use Markdown.

1. In the docs/mkdocs.yml , in the `pages` section add a new line that has:
  `- Lyapunov Exponents: lyapunovs.md`
2. Create a file called `lyapunovs.md` in the docs/src folder
3. Edit/fill this file using the [markdown syntax](https://guides.github.com/features/mastering-markdown/)

Everything else is taken care of automatically!

**Comment by Datseris** [comment]
@dapias I just saw the source code for the lyapunov function. 

I just have to let you know that any code executed inside the `try` blocks is significantly slower. This doesn't matter for your PR, but if at some point you want to make the code faster for your work, this is where to start IMO.

**Comment by dapias** [comment]
Alright, many thanks for the feedback. I refactored the code inside `try` block. In addition I added tests and documentation. Sorry I created a new PR and branch for doing that.

**Pull request closed without merging**
