### PR TITLE
Perturbation growth function

### PR DESCRIPTION
**Pull request by lhupe**
This PR will add a function `perturbationgrowth` that calculates and returns the time evolution of the perturbation vector associated with a given particle immediately before and after every collision.

### CODE REVIEW

**Comment by Datseris** [comment]
Hi @lhupe thanks for the PR!

> but since there is no periodic reorthonormalisation, all four time series should effectively be the same except for a transient phase

You used the word *should* so I am left wondering: have you tested this or not? If you have tested it (for at least 2 different systems) and it is as you say then we leave it as is: only return the first pert. growth.

For the return types: don't you think it would be easier to have each time point doubled (push twice : `push!(tim, tmin + count, tmin + count)` and push the vector before and after in the same return container? This would allow for easier plotting as well, since you could plot like `plot(t, norm.(ret), "o--")`.

**Comment by lhupe** [comment]
Hmm. I tried to use the email reply feature, but my message appears to be stuck somewhere. Anyway, here it is:

> You used the word should so I am left wondering: have you tested this or not? 

I'm pretty sure I tested it during my Bachelor project, but that was a
long time ago. I'll test it again.

> For the return types: don't you think it would be easier to have each time point doubled (push twice : `push!(tim, tmin + count, tmin + count)` and push the vector before and after in the same return container? This would allow for easier plotting as well, since you could plot like `plot(t, norm.(ret), "o--")`.

I agree with your second point. That was the way I had originally
implemented it, but I misunderstood your original mail on the output
format.

**Comment by lhupe** [comment]
I just compared the four different time series for a mushroom and a magnetic periodic Sinai billiard. They only differ by a very short transient and a constant factor. 
#### for a mushroom
mushrooms

#### for a magnetic periodic Sinai billiard
sinai

**Comment by Datseris** [comment]
> A simple one could use linear regression to check that perturbation growth curves and Lyapunov exponents are consistent.

Yeah this was exactly what I was thinking! Test are 100% necessary :D

**Pull request merged**
